'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import Payslip from './Payslip';
import type { PayslipData } from './Payslip';
import { MONTHS } from '@/lib/constants';
import api from '@/lib/axios';

interface PayslipReviewProps {
  payslip: any;
  onClose: () => void;
  onGenerate: () => void;
  onDownload: () => void;
}

const MONTHS_SHORT = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];

export function PayslipReview({ payslip, onClose, onGenerate, onDownload }: PayslipReviewProps) {
  const [companyProfile, setCompanyProfile] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get('/settings/company')
      .then(res => setCompanyProfile(res.data?.data || res.data?.companyProfile || null))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  if (!payslip) return null;

  const emp = payslip.employee || {};
  const monthName = MONTHS[(payslip.month || 1) - 1];
  const monthShort = MONTHS_SHORT[(payslip.month || 1) - 1];
  const monthNameFull = `${monthShort} ${payslip.year}`;
  const totalDaysInMonth = new Date(payslip.year, payslip.month, 0).getDate();

  const salaryItems = [
    { label: 'Basic Salary', amount: payslip.basicSalary || 0 },
    { label: 'HRA', amount: payslip.hra || 0 },
    { label: 'Special Allowance', amount: payslip.specialAllowance || 0 },
    { label: 'Conveyance Allowance', amount: payslip.travelAllowance || 0 },
    { label: 'Performance Allowance', amount: (payslip.medicalAllowance || 0) + (payslip.otherAllowances || 0) + (payslip.da || 0) },
  ];

  const deductionItems = [
    { label: 'EPF Contribution', amount: payslip.pfDeduction || 0 },
    { label: 'Professional Tax', amount: payslip.professionalTax || 0 },
    { label: 'ESI', amount: payslip.esiDeduction || 0 },
    { label: 'TDS', amount: payslip.incomeTax || 0 },
    { label: 'Advance recovery /loan recovery', amount: payslip.advanceDeduction || 0 },
  ];

  const totalSalary = payslip.totalEarnings || payslip.grossSalary || 0;
  const netSalary = payslip.netSalary || 0;

  const payslipData: PayslipData = {
    logoUrl: '/logo_pdf.PNG',
    companyName: companyProfile?.companyName || '',
    companyNameLine2: companyProfile?.nameLine2 || '',
    companyTagline: companyProfile?.tagline || '',
    companyWebsite: companyProfile?.website || '',
    monthLabel: monthNameFull,
    periodLabel: `01 ${monthShort} to ${totalDaysInMonth} ${monthShort}`,
    payslipNo: `PAY-${payslip.year}-${String(payslip.month).padStart(2, '0')}-${emp.employeeCode || '0001'}`,
    employeeName: emp.employeeName || '\u2014',
    employeeCode: emp.employeeCode || '\u2014',
    department: emp.department || '\u2014',
    designation: emp.designation || '\u2014',
    employmentType: emp.employmentStatus || '\u2014',
    category: emp.category || emp.department || '\u2014',
    panNo: emp.panNumber || '\u2014',
    doj: emp.joiningDate ? new Date(emp.joiningDate).toLocaleDateString('en-IN', { day: '2-digit', month: '2-digit', year: 'numeric' }) : '\u2014',
    aadharNo: emp.aadharNumber || '\u2014',
    uan: emp.uanNumber || '\u2014',
    payMode: 'Online Payment',
    pfAccountNo: emp.pfNumber || '\u2014',
    bankName: emp.bankName || '\u2014',
    bankAccountNo: emp.bankAccountNumber || '\u2014',
    monthDays: payslip.totalDays || totalDaysInMonth,
    totalPaidDays: payslip.payableDays || 0,
    presentDays: payslip.presentDays || 0,
    weeklyOff: payslip.weekendDays || 0,
    netPaidDays: payslip.payableDays || 0,
    absentDays: payslip.absentDays || 0,
    paidHolidays: payslip.holidayDays || 0,
    lop: payslip.lopDays && payslip.lopDays > 0 ? payslip.lopDays : 'Nil',
    workingDays: payslip.workingDays || 0,
    paidLeave: payslip.leaveDays || 0,
    salaryItems,
    deductionItems,
    totalSalary,
    totalDeductions: payslip.totalDeductions || 0,
    loanBalanceTotal: payslip.advanceDeduction && payslip.advanceDeduction > 0 ? payslip.advanceDeduction : 'Nil',
    projectDeliveryIncentive: payslip.bonus && payslip.bonus > 0 ? payslip.bonus : 'Nil',
    fullAttendanceIncentive: payslip.incentive && payslip.incentive > 0 ? payslip.incentive : 'Nil',
    totalNetSalary: netSalary,
    amountInWords: payslip.amountInWords || '\u2014',
    footerNote: 'This payslip is confidential and intended solely for the employee named above. Unauthorized sharing, modification, or misuse may be subject to Company policy.',
    autoSignedNote: `This document has been automatically generated by${companyProfile?.companyName ? ` <strong>${companyProfile.companyName}</strong>` : ''} Payroll: therefore, a signature not required.`,
  };

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto bg-white border-0">
        <DialogHeader>
          <DialogTitle className="text-xl font-bold text-gray-900">Payslip Review - {monthName} {payslip.year}</DialogTitle>
        </DialogHeader>

        {loading ? (
          <div className="flex justify-center py-12">
            <div className="w-8 h-8 border-4 border-blue-600 border-t-transparent rounded-full animate-spin" />
          </div>
        ) : (
          <Payslip data={payslipData} />
        )}

        <div className="flex justify-end gap-3 pt-4 border-t border-gray-200 mt-4">
          <Button variant="outline" onClick={onClose} className="border-gray-300 text-gray-700">Back</Button>
          {payslip.pdfPath ? (
            <Button onClick={onDownload} className="bg-blue-600 hover:bg-blue-700 text-white">Download PDF</Button>
          ) : (
            <Button onClick={onGenerate} className="bg-blue-600 hover:bg-blue-700 text-white">Generate Payslip</Button>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
