'use client';

import React from "react";

export interface SalaryLineItem {
  label: string;
  amount: number | null;
}

export interface PayslipData {
  companyName: string;
  companyNameLine2: string;
  companyTagline: string;
  companyWebsite: string;
  logoUrl?: string;

  monthLabel: string;
  periodLabel: string;
  payslipNo: string;

  employeeName: string;
  employeeCode: string;
  department: string;
  designation: string;
  employmentType: string;
  category: string;
  panNo: string;
  doj: string;
  aadharNo: string;
  uan: string;
  payMode: string;
  pfAccountNo: string;
  bankName: string;
  bankAccountNo: string;

  monthDays: number | null;
  totalPaidDays: number | null;
  presentDays: number | null;
  weeklyOff: number | null;
  netPaidDays: number | null;
  absentDays: number | null;
  paidHolidays: number | null;
  lop: number | null | string;
  workingDays: number | null;
  paidLeave: number | null;

  salaryItems: SalaryLineItem[];
  deductionItems: SalaryLineItem[];
  totalSalary: number | null;
  totalDeductions: number | null;

  loanBalanceTotal: number | null | string;
  projectDeliveryIncentive: number | null | string;
  fullAttendanceIncentive: number | null | string;

  totalNetSalary: number | null;
  amountInWords: string;
  footerNote: string;
  autoSignedNote: string;
}

const blankItem = (label: string): SalaryLineItem => ({ label, amount: null });

export const defaultPayslipData: PayslipData = {
  companyName: "",
  companyNameLine2: "",
  companyTagline: "",
  companyWebsite: "",

  monthLabel: "MONTH YYYY",
  periodLabel: "1 \u2014 31",
  payslipNo: "PAY-0000-00-0000",

  employeeName: "\u2014",
  employeeCode: "\u2014",
  department: "\u2014",
  designation: "\u2014",
  employmentType: "\u2014",
  category: "\u2014",
  panNo: "\u2014",
  doj: "\u2014",
  aadharNo: "\u2014",
  uan: "\u2014",
  payMode: "\u2014",
  pfAccountNo: "\u2014",
  bankName: "\u2014",
  bankAccountNo: "\u2014",

  monthDays: null,
  totalPaidDays: null,
  presentDays: null,
  weeklyOff: null,
  netPaidDays: null,
  absentDays: null,
  paidHolidays: null,
  lop: null,
  workingDays: null,
  paidLeave: null,

  salaryItems: [
    blankItem("Basic Salary"),
    blankItem("HRA"),
    blankItem("Special Allowance"),
    blankItem("Conveyance Allowance"),
    blankItem("Performance Allowance"),
  ],
  deductionItems: [
    blankItem("EPF Contribution"),
    blankItem("Professional Tax"),
    blankItem("ESI"),
    blankItem("TDS"),
    blankItem("Advance recovery /loan recovery"),
  ],
  totalSalary: null,
  totalDeductions: null,

  loanBalanceTotal: null,
  projectDeliveryIncentive: null,
  fullAttendanceIncentive: null,

  totalNetSalary: null,
  amountInWords: "\u2014",
  footerNote: "This payslip is confidential and intended solely for the employee named above. Unauthorized sharing, modification, or misuse may be subject to Company policy.",
  autoSignedNote: "This document has been automatically generated by the Payroll: therefore, a signature not required.",
};

const inr = (n: number | null) => "\u20B9 " + (n ?? 0);

const fmt = (n: number | null): string => {
  if (n === null || n === undefined) return "";
  return Number(n).toLocaleString("en-IN");
};

const fmtOrNil = (n: number | null | string): string => {
  if (n === null || n === undefined || n === "" || n === 0) return "Nil";
  if (typeof n === "string") return n;
  return Number(n).toLocaleString("en-IN");
};

interface PayslipProps {
  data?: Partial<PayslipData>;
}

const Payslip: React.FC<PayslipProps> = ({ data }) => {
  const d: PayslipData = { ...defaultPayslipData, ...data };

  const maxRows = Math.max(d.salaryItems.length, d.deductionItems.length);

  return (
    <div style={styles.page}>
      <div style={styles.header}>
        <div style={styles.logo}>
          <img src={d.logoUrl || "/logo_pdf.PNG"} alt="Logo" style={styles.logoImg} />
        </div>
        <div style={styles.title}><h1 style={styles.titleH1}>Payslip</h1></div>
        <div style={styles.period}>
          Payslip For the Month
          <strong style={styles.periodStrong}>{d.monthLabel}</strong>
          ({d.periodLabel})
        </div>
      </div>

      <div style={styles.detailsRow}>
        <div style={{ flex: 1 }}>
          <div style={styles.sectionLabel}>Employee Details</div>
          <div style={styles.detailsGrid}>
            <div><span style={styles.label}>Employee name</span>: {d.employeeName}</div>
            <div><span style={styles.label}>Employee Code</span>: {d.employeeCode}</div>
            <div><span style={styles.label}>Department</span>: {d.department}</div>
            <div><span style={styles.label}>Designation</span>: {d.designation}</div>
            <div><span style={styles.label}>Employment Type</span>: {d.employmentType}</div>
            <div><span style={styles.label}>Category</span>: {d.category}</div>
            <div><span style={styles.label}>PAN No</span>: {d.panNo}</div>
            <div><span style={styles.label}>DOJ</span>: {d.doj}</div>
            <div><span style={styles.label}>Aadhar No.</span>: {d.aadharNo}</div>
            <div><span style={styles.label}>UAN</span>: {d.uan}</div>
            <div><span style={styles.label}>Pay Mode</span>: {d.payMode}</div>
            <div><span style={styles.label}>PF A/c No</span>: {d.pfAccountNo}</div>
            <div><span style={styles.label}>Bank Name</span>: {d.bankName}</div>
            <div><span style={styles.label}>Bank A/c No</span>: {d.bankAccountNo}</div>
          </div>
        </div>
        <div>
          <div style={styles.payslipNo}>Payslip No&nbsp;&nbsp;: {d.payslipNo}</div>
          <div style={styles.netPayableBox}>
            <div style={styles.netPayableAmount}>{inr(d.totalNetSalary)}</div>
            <div style={styles.netPayableLabel}>TOTAL NET PAYABLE</div>
          </div>
        </div>
      </div>

      <div style={styles.attendance}>
        <div style={styles.sectionLabel}>Attendance Summary</div>
        <div style={styles.attendanceGrid}>
          <div><span style={styles.label}>Month Days</span>: <strong>{d.monthDays ?? "\u2014"}</strong></div>
          <div><span style={styles.label}>Total Paid Days</span>: <strong>{d.totalPaidDays ?? "\u2014"}</strong></div>
          <div><span style={styles.label}>Present Days</span>: <strong>{d.presentDays ?? "\u2014"}</strong></div>
          <div><span style={styles.label}>Weekly-Off</span>: <strong>{d.weeklyOff ?? "\u2014"}</strong></div>
          <div><span style={styles.label}>Net Paid Days</span>: <strong>{d.netPaidDays ?? "\u2014"}</strong></div>
          <div><span style={styles.label}>Absent Days</span>: <strong>{d.absentDays ?? "\u2014"}</strong></div>
          <div><span style={styles.label}>Paid Holidays</span>: <strong>{d.paidHolidays ?? "\u2014"}</strong></div>
          <div><span style={styles.label}>LOP</span>: <strong>{d.lop ?? "Nil"}</strong></div>
          <div></div>
          <div><span style={styles.label}>Working Days</span>: <strong>{d.workingDays ?? "\u2014"}</strong></div>
          <div><span style={styles.label}>Paid leave</span>: <strong>{d.paidLeave ?? "\u2014"}</strong></div>
        </div>
      </div>

      <hr style={styles.dashed} />

      <div style={styles.salaryBox}>
        <table style={styles.salaryTable}>
          <thead>
            <tr>
              <th style={styles.th}>Salary</th>
              <th style={styles.thAmt}>Amount Rs.</th>
              <th style={styles.th}>Deductions</th>
              <th style={styles.thAmt}>Amount Rs.</th>
            </tr>
          </thead>
          <tbody>
            {Array.from({ length: maxRows }).map((_, i) => {
              const s = d.salaryItems[i];
              const ded = d.deductionItems[i];
              return (
                <tr key={i}>
                  <td style={styles.td}>{s ? s.label : ""}</td>
                  <td style={styles.tdAmt}>{s ? fmt(s.amount) : ""}</td>
                  <td style={styles.td}>{ded ? ded.label : ""}</td>
                  <td style={styles.tdAmt}>{ded ? fmtOrNil(ded.amount) : ""}</td>
                </tr>
              );
            })}
            <tr>
              <td style={styles.tdTotal}>Total Salary</td>
              <td style={styles.tdTotalAmt}>{fmt(d.totalSalary)}</td>
              <td style={styles.tdTotal}>Total Deductions</td>
              <td style={styles.tdTotalAmt}>{fmt(d.totalDeductions)}</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div style={styles.bonusLoan}>
        <div style={styles.bonusBlock}>
          <strong>Loan Balance</strong>
          Total : {fmtOrNil(d.loanBalanceTotal)}
        </div>
      </div>

      <div style={styles.netTotal}>
        <div style={styles.netTotalDesc}>
          TOTAL NET SALARY
          <small style={styles.netTotalSmall}>Gross Salary − Total Deductions + Bonus</small>
        </div>
        <div style={styles.netTotalAmount}>{inr(d.totalNetSalary)}</div>
      </div>

      <div style={styles.words}>AMOUNT IN WORDS : {d.amountInWords}</div>

      <div style={styles.footerNote}>{d.footerNote}</div>
      <div style={styles.footerSign} dangerouslySetInnerHTML={{ __html: `-${d.autoSignedNote}-` }} />
    </div>
  );
};

const ACCENT = "#4a6fa5";
const ACCENT_BOX = "#a9c1de";
const TEXT_DARK = "#2b2b2b";
const TEXT_MUTED = "#555";
const BORDER = "#c9c9c9";

const styles: Record<string, React.CSSProperties> = {
  page: {
    maxWidth: 850,
    margin: "0 auto",
    background: "#fff",
    padding: "35px 40px",
    fontFamily: "'Segoe UI', Arial, sans-serif",
    color: TEXT_DARK,
    fontSize: 13,
    lineHeight: 1.4,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1.5px solid #333",
    paddingBottom: 15,
    marginBottom: 20,
  },
  logo: {
    width: 110,
    height: 110,
    flexShrink: 0,
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  logoImg: { maxWidth: "100%", maxHeight: "100%", objectFit: "contain" as const, display: "block" },
  title: { textAlign: "center" },
  titleH1: { fontSize: 26, margin: 0, color: "#333" },
  period: { textAlign: "right" as const, fontSize: 13, color: TEXT_MUTED },
  periodStrong: { display: "block", fontSize: 15, color: "#000" },
  sectionLabel: {
    fontWeight: 700,
    fontSize: 13,
    marginBottom: 8,
    color: "#333",
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
  },
  detailsRow: { display: "flex", justifyContent: "space-between", gap: 20 },
  detailsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    rowGap: 9,
    columnGap: 15,
    fontSize: 13.5,
    flex: 1,
  },
  label: { display: "inline-block", minWidth: 118, color: TEXT_DARK },
  netPayableBox: {
    border: `1px solid ${BORDER}`,
    borderRadius: 12,
    textAlign: "center" as const,
    minWidth: 210,
    overflow: "hidden",
    background: "#fff",
    padding: 8,
  },
  netPayableAmount: {
    background: ACCENT_BOX,
    fontSize: 26,
    fontWeight: 700,
    color: "#1a1a1a",
    padding: "18px 18px 18px 34px",
    borderRadius: 6,
    position: "relative" as const,
  },
  netPayableLabel: {
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0.3,
    color: "#333",
    padding: "12px 0 6px",
    background: "#fff",
  },
  payslipNo: { textAlign: "right" as const, fontSize: 13, color: TEXT_DARK, marginBottom: 10 },
  attendance: { marginTop: 18, borderTop: `1px dashed ${BORDER}`, paddingTop: 14 },
  attendanceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    rowGap: 6,
    fontSize: 13.5,
  },
  dashed: { border: "none", borderTop: `1px dashed ${BORDER}`, margin: "20px 0" },
  salaryBox: {
    border: `1.5px solid ${BORDER}`,
    borderRadius: 10,
    padding: "18px 22px 10px",
  },
  salaryTable: { width: "100%", borderCollapse: "collapse", fontSize: 14 },
  th: {
    textAlign: "left" as const,
    fontSize: 14,
    fontWeight: 700,
    color: "#222",
    borderBottom: `1.5px solid ${BORDER}`,
    padding: "0 6px 12px",
  },
  thAmt: {
    textAlign: "left" as const,
    fontSize: 14,
    fontWeight: 700,
    color: "#222",
    borderBottom: `1.5px solid ${BORDER}`,
    padding: "0 6px 12px 40px",
  },
  td: { padding: "11px 6px", verticalAlign: "top" as const },
  tdAmt: { padding: "11px 6px 11px 40px", verticalAlign: "top" as const },
  tdTotal: {
    borderTop: `1.5px dashed ${BORDER}`,
    fontWeight: 700,
    padding: "14px 6px 11px",
  },
  tdTotalAmt: {
    borderTop: `1.5px dashed ${BORDER}`,
    fontWeight: 700,
    padding: "14px 6px 11px 40px",
  },
  bonusLoan: {
    display: "flex",
    justifyContent: "flex-start",
    marginTop: 20,
    fontSize: 14,
    flexWrap: "wrap" as const,
    gap: 60,
  },
  bonusBlock: { display: "flex", flexDirection: "column" as const, gap: 4 },
  netTotal: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: "#fff",
    border: `1px solid ${BORDER}`,
    borderRadius: 12,
    padding: "16px 22px",
    marginTop: 24,
  },
  netTotalDesc: { fontWeight: 700, fontSize: 15, color: "#1a1a1a" },
  netTotalSmall: { display: "block", fontWeight: 400, color: "#333", fontSize: 12 },
  netTotalAmount: {
    fontSize: 24,
    fontWeight: 700,
    color: "#1a1a1a",
    background: ACCENT_BOX,
    borderRadius: 6,
    padding: "12px 22px",
  },
  words: { marginTop: 14, fontSize: 13 },
  footerNote: { marginTop: 20, fontSize: 13, color: TEXT_MUTED, textAlign: "center" as const, lineHeight: 1.5 },
  footerSign: { marginTop: 14, borderTop: `1px solid ${BORDER}`, paddingTop: 10, textAlign: "center" as const, fontSize: 11.5, color: TEXT_MUTED },
};

export default Payslip;
